/*
 * This Java source file was generated by the Gradle 'init' task.
 */

import java.lang.*; 

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }

    public static int max(int a, int b) {
        if (a > b) return a;
        return b;
    }

    public static int min(int a, int b) {
        if (a < b) return a;
        return b;
    }

    public static int[] addVector(int[] a, int[] b) {
        if (a.length != b.length)
            return null;

        int[] ans = new int[a.length];
        for (int i = 0; i < a.length; ++i) {
            ans[i] = a[i] + b[i];
        }
        return ans;
    }

    public static int innerProduct(int[] a, int[] b) throws Exception {
        if (a.length != b.length) 
            throw new Exception("Dimension error!"); 
        int ans = 0; 
        for (int i = 0; i < a.length; ++i) {
            ans += a[i] * b[i];
        }
        return ans; 
    }

    public static double vectorLength(int[] a) {
        int sum = 0; 
        for (int i: a) {
            sum += i * i;
        }
        return Math.sqrt(sum);
    }

    public static int[] scalar(int[] u, int a) {
        int[] result = new int[u.length]; 

        for (int i=0; i < u.length; ++i) {
            result[i] = a * u[i];
        }
        return result; 
    }
}
