/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test public void testAppHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }
    @Test public void testAdd() {
        assertEquals(2, 1+1);
        assertEquals(-2, -1+(-1));
    }
    @Test public void testSubstract() {
        assertEquals(0, 1-1);
        assertEquals(1, -1-(-2));
    }
    @Test public void testMultiply() {
        assertEquals(2, 1*2);
        assertEquals(2, -1*(-2));
    }
    @Test public void testMax() {
        assertEquals(2, App.max(1, 2));
    }

    @Test public void testMin() {
        assertEquals(1, App.min(1, 2));
    }
}
