/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }

    public static int max(int a, int b) {
        if (a > b) return a;
        return b;
    }

    public static int min(int a, int b) {
        if (a < b) return a;
        return b;
    }
}
